name       : python-flask-socketio
version    : 5.1.1
release    : 1
source     :
    - https://pypi.io/packages/source/F/Flask-SocketIO/Flask-SocketIO-5.1.1.tar.gz : 1efdaacc7a26e94f2b197a80079b1058f6aa644a6094c0a322349e2b9c41f6b1
license    : MIT
component  : programming.python
summary    : Socket.IO integration for Flask applications
description: |
    This integrates Socket.IO into Flask.
rundeps    :
    - flask
    - python-socketio
build      : |
    %python3_setup
install    : |
    %python3_install
